# Generated by Django 2.1.7 on 2019-04-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField()),
                ('date_completed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1000)),
                ('deleted', models.BooleanField(default=False)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_answer_text', models.CharField(max_length=1000)),
                ('deleted', models.BooleanField(default=False)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=250, unique=True)),
                ('quest_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('quest_points_earned', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_type', models.CharField(max_length=45)),
                ('deleted', models.BooleanField(default=False)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Quest')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ldap', models.CharField(max_length=45)),
                ('user_first_name', models.CharField(max_length=45)),
                ('user_last_name', models.CharField(max_length=45)),
                ('user_email', models.CharField(max_length=45)),
                ('user_manager_ldap', models.CharField(max_length=45)),
                ('user_director_ldap', models.CharField(max_length=45)),
                ('user_points', models.IntegerField()),
                ('exempt', models.IntegerField()),
                ('current_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Quest')),
            ],
        ),
        migrations.AddField(
            model_name='incorrectanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Question'),
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Question'),
        ),
        migrations.AddField(
            model_name='completedquest',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Quest'),
        ),
        migrations.AddField(
            model_name='completedquest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.User'),
        ),
    ]
