# Generated by Django 2.1.7 on 2019-04-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exempt',
            field=models.BooleanField(default=False),
        ),
    ]
