# Generated by Django 2.1.7 on 2019-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='potato',
            field=models.CharField(default='potato', max_length=100),
            preserve_default=False,
        ),
    ]
