# Generated by Django 2.1.7 on 2019-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend',
            field=models.CharField(max_length=5),
        ),
    ]
