# Generated by Django 2.1.7 on 2019-05-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0002_project_potato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='potato',
        ),
    ]
