# Generated by Django 2.1.7 on 2019-05-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0002_auto_20190515_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friend',
            new_name='user_reset_password',
        ),
    ]
