# Generated by Django 2.1.7 on 2019-04-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0003_auto_20190422_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Quest'),
        ),
    ]
