# Generated by Django 2.1.7 on 2019-05-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0003_remove_project_potato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=1000)),
                ('video_type', models.CharField(choices=[('Youtube', 'Youtube'), ('Personal', 'Personal')], max_length=1000)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Quest')),
            ],
        ),
    ]
