# Generated by Django 2.1.7 on 2019-04-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0004_auto_20190422_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_path_number',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
