# Generated by Django 2.1.7 on 2019-05-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(max_length=1000),
        ),
    ]
