# Generated by Django 2.1.7 on 2019-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0004_auto_20190515_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_reset_password',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
