# Generated by Django 2.1.7 on 2019-04-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0005_quest_quest_path_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_path_number',
            field=models.IntegerField(unique=True),
        ),
    ]
