# Generated by Django 2.1.7 on 2019-05-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0005_auto_20190515_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_reset_password',
            new_name='user_reset_password_pin',
        ),
    ]
