# Generated by Django 2.1.7 on 2019-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0005_auto_20190510_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('Youtube', 'Youtube'), ('Personal', 'Personal')], max_length=1000),
        ),
    ]
