# Generated by Django 2.1.7 on 2019-05-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0006_auto_20190515_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ldap', models.CharField(max_length=45)),
                ('admin_first_name', models.CharField(max_length=45)),
                ('admin_last_name', models.CharField(max_length=45)),
                ('admin_email', models.CharField(max_length=45)),
                ('admin_password', models.CharField(max_length=45)),
                ('admin_reset_password_pin', models.CharField(default=None, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Admin')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_director_ldap',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_manager_ldap',
        ),
    ]
