# Generated by Django 2.1.7 on 2019-04-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0006_auto_20190422_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quest_extension.Quest'),
        ),
    ]
