# Generated by Django 2.1.7 on 2019-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0007_auto_20190516_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_reset_password_pin',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
