# Generated by Django 2.1.7 on 2019-04-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0010_quest_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Project'),
        ),
    ]
