# Generated by Django 2.1.7 on 2019-04-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0011_auto_20190426_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_name',
            field=models.CharField(max_length=250),
        ),
    ]
