# Generated by Django 2.1.7 on 2019-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0012_auto_20190517_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_admin_pin',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
