# Generated by Django 2.1.7 on 2019-04-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0013_auto_20190426_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectlyAnsweredQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.User')),
            ],
        ),
    ]
