# Generated by Django 2.1.7 on 2019-05-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0013_auto_20190517_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_random_phrase',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
