# Generated by Django 2.1.7 on 2019-05-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0014_auto_20190517_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedquest',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='completedquest',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompletedQuest',
        ),
    ]
