# Generated by Django 2.1.7 on 2019-04-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0015_currentquest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_quest',
        ),
    ]
