# Generated by Django 2.1.7 on 2019-04-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0016_remove_user_current_quest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentQuest',
            new_name='UserProject',
        ),
    ]
