# Generated by Django 2.1.7 on 2019-05-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0017_question_undo_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='undo_time',
            new_name='undo_delete_time',
        ),
    ]
