# Generated by Django 2.1.7 on 2019-04-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0017_auto_20190430_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
