# Generated by Django 2.1.7 on 2019-05-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0018_auto_20190528_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='undo_delete_time',
            new_name='delete_time',
        ),
    ]
