# Generated by Django 2.1.7 on 2019-04-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0018_userproject_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_points',
        ),
    ]
