# Generated by Django 2.1.7 on 2019-05-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0019_auto_20190528_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_reset_password_pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_reset_password_pin',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
