# Generated by Django 2.1.7 on 2019-04-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0020_project_project_random_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_random_phrase',
            field=models.CharField(max_length=255),
        ),
    ]
