# Generated by Django 2.1.7 on 2019-05-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0020_auto_20190528_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctlyansweredquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='correctlyansweredquestion',
            name='userproject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quest_extension.UserProject'),
        ),
    ]
