# Generated by Django 2.1.7 on 2019-05-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0021_auto_20190529_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_type',
        ),
    ]
