# Generated by Django 2.1.7 on 2019-04-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0021_auto_20190430_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exempt',
        ),
    ]
