# Generated by Django 2.1.7 on 2019-05-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0022_remove_video_video_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctanswer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='incorrectanswer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='deleted',
        ),
    ]
