# Generated by Django 2.1.7 on 2019-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0023_auto_20190430_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='password', max_length=45),
        ),
    ]
