# Generated by Django 2.1.7 on 2019-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0026_auto_20190531_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='api_url',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
