# Generated by Django 2.1.7 on 2019-05-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0027_project_project_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_editable',
            field=models.BooleanField(),
        ),
    ]
