# Generated by Django 2.1.7 on 2019-06-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0028_auto_20190603_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminproject',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
