# Generated by Django 2.1.7 on 2019-06-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0030_userproject_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
