# Generated by Django 2.1.7 on 2019-06-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0031_project_time_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='time_modified',
        ),
    ]
