# Generated by Django 2.0.13 on 2019-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0032_remove_project_time_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_picture_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
