# Generated by Django 2.0.13 on 2019-06-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0034_auto_20190613_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctlyansweredquestion',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
