# Generated by Django 2.0.13 on 2019-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0036_remove_correctlyansweredquestion_time_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='times_points_added',
            field=models.DateTimeField(null=True),
        ),
    ]
