# Generated by Django 2.0.13 on 2019-06-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0037_userproject_times_points_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_completed', models.DateTimeField(null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.Quest')),
            ],
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='times_points_added',
        ),
        migrations.AddField(
            model_name='completedquest',
            name='user_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_extension.UserProject'),
        ),
    ]
