# Generated by Django 2.0.13 on 2019-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0039_auto_20190619_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_picture_url',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
