# Generated by Django 2.0.13 on 2019-06-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0040_auto_20190619_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_picture_url',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
