# Generated by Django 2.0.13 on 2019-06-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_extension', '0041_auto_20190620_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='answer_text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='incorrectanswer',
            name='answer_text',
            field=models.CharField(max_length=10000),
        ),
    ]
